// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package masterdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Favorite struct {
	ClientID  int64              `json:"client_id"`
	MasterID  int64              `json:"master_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MasterProfile struct {
	UserID      int64              `json:"user_id"`
	City        pgtype.Text        `json:"city"`
	Bio         pgtype.Text        `json:"bio"`
	RatingAvg   float64            `json:"rating_avg"`
	RatingCount int32              `json:"rating_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

type MasterSpecialization struct {
	MasterUserID int64 `json:"master_user_id"`
	ServiceID    int64 `json:"service_id"`
}

type Message struct {
	ID        int64              `json:"id"`
	RequestID int64              `json:"request_id"`
	SenderID  int64              `json:"sender_id"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type Payment struct {
	ID          int64              `json:"id"`
	RequestID   int64              `json:"request_id"`
	Amount      float64            `json:"amount"`
	PlatformFee float64            `json:"platform_fee"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type RequestOffer struct {
	ID        int64              `json:"id"`
	RequestID int64              `json:"request_id"`
	MasterID  int64              `json:"master_id"`
	Price     float64            `json:"price"`
	Comment   pgtype.Text        `json:"comment"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RequestStatusHistory struct {
	ID         int64              `json:"id"`
	RequestID  int64              `json:"request_id"`
	FromStatus pgtype.Text        `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	ChangedBy  int64              `json:"changed_by"`
	Comment    pgtype.Text        `json:"comment"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Review struct {
	ID        int64              `json:"id"`
	RequestID int64              `json:"request_id"`
	ClientID  int64              `json:"client_id"`
	MasterID  int64              `json:"master_id"`
	Rating    int16              `json:"rating"`
	Comment   pgtype.Text        `json:"comment"`
	Hidden    bool               `json:"hidden"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Service struct {
	ID          int64              `json:"id"`
	CategoryID  int64              `json:"category_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	PriceFrom   *float64           `json:"price_from"`
	PriceTo     *float64           `json:"price_to"`
	Unit        pgtype.Text        `json:"unit"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ImageUrl    pgtype.Text        `json:"image_url"`
}

type ServiceCategory struct {
	ID               int64              `json:"id"`
	ParentCategoryID pgtype.Int8        `json:"parent_category_id"`
	Name             string             `json:"name"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ServiceRequest struct {
	ID           int64              `json:"id"`
	ClientID     int64              `json:"client_id"`
	ServiceID    int64              `json:"service_id"`
	Description  string             `json:"description"`
	AddressText  string             `json:"address_text"`
	Latitude     pgtype.Float8      `json:"latitude"`
	Longitude    pgtype.Float8      `json:"longitude"`
	Status       string             `json:"status"`
	MasterID     pgtype.Int8        `json:"master_id"`
	AgreedPrice  *float64           `json:"agreed_price"`
	CancelReason pgtype.Text        `json:"cancel_reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	FullName     pgtype.Text        `json:"full_name"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
