// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package masterdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMasterProfiles = `-- name: CountMasterProfiles :one
SELECT COUNT(*)::bigint AS count
FROM master_profiles
`

func (q *Queries) CountMasterProfiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMasterProfiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMasterProfile = `-- name: GetMasterProfile :one
SELECT user_id, city, bio, rating_avg, rating_count, created_at, updated_at
FROM master_profiles
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetMasterProfile(ctx context.Context, userID int64) (MasterProfile, error) {
	row := q.db.QueryRow(ctx, getMasterProfile, userID)
	var i MasterProfile
	err := row.Scan(
		&i.UserID,
		&i.City,
		&i.Bio,
		&i.RatingAvg,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMasterProfiles = `-- name: ListMasterProfiles :many
SELECT user_id, city, bio, rating_avg, rating_count, created_at, updated_at
FROM master_profiles
ORDER BY rating_avg DESC, created_at DESC
LIMIT $2 OFFSET $1
`

type ListMasterProfilesParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

func (q *Queries) ListMasterProfiles(ctx context.Context, arg ListMasterProfilesParams) ([]MasterProfile, error) {
	rows, err := q.db.Query(ctx, listMasterProfiles, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterProfile{}
	for rows.Next() {
		var i MasterProfile
		if err := rows.Scan(
			&i.UserID,
			&i.City,
			&i.Bio,
			&i.RatingAvg,
			&i.RatingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMasterReview = `-- name: RecordMasterReview :one
UPDATE master_profiles
SET rating_avg = ROUND(((rating_avg * rating_count) + $1::numeric) / (rating_count + 1), 2),
    rating_count = rating_count + 1,
    updated_at = NOW()
WHERE user_id = $2
RETURNING user_id, city, bio, rating_avg, rating_count, created_at, updated_at
`

type RecordMasterReviewParams struct {
	Rating float64 `json:"rating"`
	UserID int64   `json:"user_id"`
}

// Atomic running-average update: new_avg = (avg*count + rating) / (count+1).
// Done in SQL rather than read-modify-write in Go to avoid a lost update
// race between two reviews landing concurrently for the same master.
func (q *Queries) RecordMasterReview(ctx context.Context, arg RecordMasterReviewParams) (MasterProfile, error) {
	row := q.db.QueryRow(ctx, recordMasterReview, arg.Rating, arg.UserID)
	var i MasterProfile
	err := row.Scan(
		&i.UserID,
		&i.City,
		&i.Bio,
		&i.RatingAvg,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMasterProfile = `-- name: UpsertMasterProfile :one
INSERT INTO master_profiles (user_id, city, bio)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET city = excluded.city, bio = excluded.bio, updated_at = NOW()
RETURNING user_id, city, bio, rating_avg, rating_count, created_at, updated_at
`

type UpsertMasterProfileParams struct {
	UserID int64       `json:"user_id"`
	City   pgtype.Text `json:"city"`
	Bio    pgtype.Text `json:"bio"`
}

func (q *Queries) UpsertMasterProfile(ctx context.Context, arg UpsertMasterProfileParams) (MasterProfile, error) {
	row := q.db.QueryRow(ctx, upsertMasterProfile, arg.UserID, arg.City, arg.Bio)
	var i MasterProfile
	err := row.Scan(
		&i.UserID,
		&i.City,
		&i.Bio,
		&i.RatingAvg,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
