// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: specializations.sql

package masterdb

import (
	"context"
)

const addMasterSpecialization = `-- name: AddMasterSpecialization :exec
INSERT INTO master_specializations (master_user_id, service_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddMasterSpecializationParams struct {
	MasterUserID int64 `json:"master_user_id"`
	ServiceID    int64 `json:"service_id"`
}

func (q *Queries) AddMasterSpecialization(ctx context.Context, arg AddMasterSpecializationParams) error {
	_, err := q.db.Exec(ctx, addMasterSpecialization, arg.MasterUserID, arg.ServiceID)
	return err
}

const deleteMasterSpecializations = `-- name: DeleteMasterSpecializations :exec
DELETE FROM master_specializations WHERE master_user_id = $1
`

func (q *Queries) DeleteMasterSpecializations(ctx context.Context, masterUserID int64) error {
	_, err := q.db.Exec(ctx, deleteMasterSpecializations, masterUserID)
	return err
}

const listMasterSpecializationIDs = `-- name: ListMasterSpecializationIDs :many
SELECT service_id
FROM master_specializations
WHERE master_user_id = $1
ORDER BY service_id
`

func (q *Queries) ListMasterSpecializationIDs(ctx context.Context, masterUserID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listMasterSpecializationIDs, masterUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var service_id int64
		if err := rows.Scan(&service_id); err != nil {
			return nil, err
		}
		items = append(items, service_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const masterHasSpecialization = `-- name: MasterHasSpecialization :one
SELECT EXISTS(
    SELECT 1
    FROM master_specializations
    WHERE master_user_id = $1 AND service_id = $2
) AS exists
`

type MasterHasSpecializationParams struct {
	MasterUserID int64 `json:"master_user_id"`
	ServiceID    int64 `json:"service_id"`
}

func (q *Queries) MasterHasSpecialization(ctx context.Context, arg MasterHasSpecializationParams) (bool, error) {
	row := q.db.QueryRow(ctx, masterHasSpecialization, arg.MasterUserID, arg.ServiceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
