version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: curs3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/curs3
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZAoKQ1NIZFV0bGtLSmRWVmhRPT0KVGhpcyBpcyBhIHZlcnkgbG9uZyBhbmQgc2VjdXJlIHNlY3JldCBrZXkgZm9yIEpXVCBhdXRoZW50aWNhdGlvbiBpbiBteSBTcHJpbmcgQm9vdCBhcHBsaWNhdGlvbjIwMjQ=
      FILE_UPLOAD_DIR: uploads
    ports:
      - "8080:8080"
    volumes:
      - uploads:/app/uploads

volumes:
  db-data:
  uploads:
