// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package taskdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignTask = `-- name: AssignTask :one
UPDATE tasks
SET assignee_id = $1, updated_at = NOW()
WHERE id = $2 AND tenant_id = $3 AND status = 'PENDING'
RETURNING id, type, tenant_id, address_id, status, due_date, assignee_id,
    created_at, updated_at, completed_at, canceled_at, cancel_reason
`

type AssignTaskParams struct {
	AssigneeID pgtype.Int8 `json:"assignee_id"`
	ID         int64       `json:"id"`
	TenantID   int64       `json:"tenant_id"`
}

func (q *Queries) AssignTask(ctx context.Context, arg AssignTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, assignTask, arg.AssigneeID, arg.ID, arg.TenantID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TenantID,
		&i.AddressID,
		&i.Status,
		&i.DueDate,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CancelReason,
	)
	return i, err
}

const cancelTask = `-- name: CancelTask :one
UPDATE tasks
SET status = 'CANCELED', canceled_at = NOW(), cancel_reason = $1, updated_at = NOW()
WHERE id = $2 AND tenant_id = $3 AND status IN ('PENDING', 'IN_PROGRESS')
RETURNING id, type, tenant_id, address_id, status, due_date, assignee_id,
    created_at, updated_at, completed_at, canceled_at, cancel_reason
`

type CancelTaskParams struct {
	CancelReason pgtype.Text `json:"cancel_reason"`
	ID           int64       `json:"id"`
	TenantID     int64       `json:"tenant_id"`
}

func (q *Queries) CancelTask(ctx context.Context, arg CancelTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, cancelTask, arg.CancelReason, arg.ID, arg.TenantID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TenantID,
		&i.AddressID,
		&i.Status,
		&i.DueDate,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CancelReason,
	)
	return i, err
}

const completeTask = `-- name: CompleteTask :one
UPDATE tasks
SET status = 'COMPLETED', completed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND status = 'IN_PROGRESS'
RETURNING id, type, tenant_id, address_id, status, due_date, assignee_id,
    created_at, updated_at, completed_at, canceled_at, cancel_reason
`

type CompleteTaskParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, completeTask, arg.ID, arg.TenantID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TenantID,
		&i.AddressID,
		&i.Status,
		&i.DueDate,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CancelReason,
	)
	return i, err
}

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*)::bigint AS count
FROM tasks
WHERE tenant_id = $1
  AND ($2::text = '' OR status = $2::text)
  AND ($3::text = '' OR type = $3::text)
  AND ($4::bigint = 0 OR assignee_id = $4::bigint)
`

type CountTasksParams struct {
	TenantID   int64  `json:"tenant_id"`
	Status     string `json:"status"`
	TaskType   string `json:"task_type"`
	AssigneeID int64  `json:"assignee_id"`
}

func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks,
		arg.TenantID,
		arg.Status,
		arg.TaskType,
		arg.AssigneeID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (type, tenant_id, address_id, status, due_date, assignee_id)
VALUES ($1, $2, $3, 'PENDING', $4, $5)
RETURNING id, type, tenant_id, address_id, status, due_date, assignee_id,
    created_at, updated_at, completed_at, canceled_at, cancel_reason
`

type CreateTaskParams struct {
	Type       string      `json:"type"`
	TenantID   int64       `json:"tenant_id"`
	AddressID  int64       `json:"address_id"`
	DueDate    pgtype.Date `json:"due_date"`
	AssigneeID pgtype.Int8 `json:"assignee_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Type,
		arg.TenantID,
		arg.AddressID,
		arg.DueDate,
		arg.AssigneeID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TenantID,
		&i.AddressID,
		&i.Status,
		&i.DueDate,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CancelReason,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, type, tenant_id, address_id, status, due_date, assignee_id,
    created_at, updated_at, completed_at, canceled_at, cancel_reason
FROM tasks
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetTaskByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.TenantID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TenantID,
		&i.AddressID,
		&i.Status,
		&i.DueDate,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CancelReason,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, type, tenant_id, address_id, status, due_date, assignee_id,
    created_at, updated_at, completed_at, canceled_at, cancel_reason
FROM tasks
WHERE tenant_id = $1
  AND ($2::text = '' OR status = $2::text)
  AND ($3::text = '' OR type = $3::text)
  AND ($4::bigint = 0 OR assignee_id = $4::bigint)
ORDER BY
    CASE status WHEN 'PENDING' THEN 0 WHEN 'IN_PROGRESS' THEN 1 ELSE 2 END,
    due_date NULLS LAST,
    created_at DESC
LIMIT $6 OFFSET $5
`

type ListTasksParams struct {
	TenantID   int64  `json:"tenant_id"`
	Status     string `json:"status"`
	TaskType   string `json:"task_type"`
	AssigneeID int64  `json:"assignee_id"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.TenantID,
		arg.Status,
		arg.TaskType,
		arg.AssigneeID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TenantID,
			&i.AddressID,
			&i.Status,
			&i.DueDate,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.CancelReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startTask = `-- name: StartTask :one
UPDATE tasks
SET status = 'IN_PROGRESS', updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND status = 'PENDING'
RETURNING id, type, tenant_id, address_id, status, due_date, assignee_id,
    created_at, updated_at, completed_at, canceled_at, cancel_reason
`

type StartTaskParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) StartTask(ctx context.Context, arg StartTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, startTask, arg.ID, arg.TenantID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TenantID,
		&i.AddressID,
		&i.Status,
		&i.DueDate,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CancelReason,
	)
	return i, err
}
