// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package requestdb

import (
	"context"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (client_id, master_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFavoriteParams struct {
	ClientID int64 `json:"client_id"`
	MasterID int64 `json:"master_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.ClientID, arg.MasterID)
	return err
}

const listFavoritesByClient = `-- name: ListFavoritesByClient :many
SELECT client_id, master_id, created_at
FROM favorites
WHERE client_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFavoritesByClient(ctx context.Context, clientID int64) ([]Favorite, error) {
	rows, err := q.db.Query(ctx, listFavoritesByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Favorite{}
	for rows.Next() {
		var i Favorite
		if err := rows.Scan(&i.ClientID, &i.MasterID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites WHERE client_id = $1 AND master_id = $2
`

type RemoveFavoriteParams struct {
	ClientID int64 `json:"client_id"`
	MasterID int64 `json:"master_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.ClientID, arg.MasterID)
	return err
}
