// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package requestdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStatusHistory = `-- name: CreateStatusHistory :exec
INSERT INTO request_status_history (request_id, from_status, to_status, changed_by, comment)
VALUES ($1, $2, $3, $4, $5)
`

type CreateStatusHistoryParams struct {
	RequestID  int64       `json:"request_id"`
	FromStatus pgtype.Text `json:"from_status"`
	ToStatus   string      `json:"to_status"`
	ChangedBy  int64       `json:"changed_by"`
	Comment    pgtype.Text `json:"comment"`
}

func (q *Queries) CreateStatusHistory(ctx context.Context, arg CreateStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, createStatusHistory,
		arg.RequestID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedBy,
		arg.Comment,
	)
	return err
}

const listStatusHistoryByRequest = `-- name: ListStatusHistoryByRequest :many
SELECT id, request_id, from_status, to_status, changed_by, comment, created_at
FROM request_status_history
WHERE request_id = $1
ORDER BY created_at
`

func (q *Queries) ListStatusHistoryByRequest(ctx context.Context, requestID int64) ([]RequestStatusHistory, error) {
	rows, err := q.db.Query(ctx, listStatusHistoryByRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestStatusHistory{}
	for rows.Next() {
		var i RequestStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedBy,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
