// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offers.sql

package requestdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptOffer = `-- name: AcceptOffer :one
UPDATE request_offers
SET status = 'ACCEPTED', updated_at = NOW()
WHERE id = $1 AND status = 'PENDING'
RETURNING id, request_id, master_id, price, comment, status, created_at, updated_at
`

func (q *Queries) AcceptOffer(ctx context.Context, id int64) (RequestOffer, error) {
	row := q.db.QueryRow(ctx, acceptOffer, id)
	var i RequestOffer
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.MasterID,
		&i.Price,
		&i.Comment,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOffer = `-- name: CreateOffer :one
INSERT INTO request_offers (request_id, master_id, price, comment, status)
VALUES ($1, $2, $3, $4, 'PENDING')
RETURNING id, request_id, master_id, price, comment, status, created_at, updated_at
`

type CreateOfferParams struct {
	RequestID int64       `json:"request_id"`
	MasterID  int64       `json:"master_id"`
	Price     float64     `json:"price"`
	Comment   pgtype.Text `json:"comment"`
}

func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) (RequestOffer, error) {
	row := q.db.QueryRow(ctx, createOffer,
		arg.RequestID,
		arg.MasterID,
		arg.Price,
		arg.Comment,
	)
	var i RequestOffer
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.MasterID,
		&i.Price,
		&i.Comment,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOfferByID = `-- name: GetOfferByID :one
SELECT id, request_id, master_id, price, comment, status, created_at, updated_at
FROM request_offers
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOfferByID(ctx context.Context, id int64) (RequestOffer, error) {
	row := q.db.QueryRow(ctx, getOfferByID, id)
	var i RequestOffer
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.MasterID,
		&i.Price,
		&i.Comment,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOffersByRequest = `-- name: ListOffersByRequest :many
SELECT id, request_id, master_id, price, comment, status, created_at, updated_at
FROM request_offers
WHERE request_id = $1
ORDER BY created_at
`

func (q *Queries) ListOffersByRequest(ctx context.Context, requestID int64) ([]RequestOffer, error) {
	rows, err := q.db.Query(ctx, listOffersByRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestOffer{}
	for rows.Next() {
		var i RequestOffer
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.MasterID,
			&i.Price,
			&i.Comment,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectOtherOffers = `-- name: RejectOtherOffers :exec
UPDATE request_offers
SET status = 'REJECTED', updated_at = NOW()
WHERE request_id = $1 AND id != $2 AND status = 'PENDING'
`

type RejectOtherOffersParams struct {
	RequestID       int64 `json:"request_id"`
	AcceptedOfferID int64 `json:"accepted_offer_id"`
}

func (q *Queries) RejectOtherOffers(ctx context.Context, arg RejectOtherOffersParams) error {
	_, err := q.db.Exec(ctx, rejectOtherOffers, arg.RequestID, arg.AcceptedOfferID)
	return err
}
