// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package requestdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignServiceRequest = `-- name: AssignServiceRequest :one
UPDATE service_requests
SET status = 'ASSIGNED', master_id = $1, agreed_price = $2, updated_at = NOW()
WHERE id = $3 AND status = 'OPEN'
RETURNING id, client_id, service_id, description, address_text, latitude, longitude, status, master_id,
    agreed_price, cancel_reason, created_at, updated_at
`

type AssignServiceRequestParams struct {
	MasterID    pgtype.Int8 `json:"master_id"`
	AgreedPrice *float64    `json:"agreed_price"`
	ID          int64       `json:"id"`
}

func (q *Queries) AssignServiceRequest(ctx context.Context, arg AssignServiceRequestParams) (ServiceRequest, error) {
	row := q.db.QueryRow(ctx, assignServiceRequest, arg.MasterID, arg.AgreedPrice, arg.ID)
	var i ServiceRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ServiceID,
		&i.Description,
		&i.AddressText,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.MasterID,
		&i.AgreedPrice,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelServiceRequest = `-- name: CancelServiceRequest :one
UPDATE service_requests
SET status = 'CANCELED', cancel_reason = $1, updated_at = NOW()
WHERE id = $2 AND status IN ('OPEN', 'ASSIGNED')
RETURNING id, client_id, service_id, description, address_text, latitude, longitude, status, master_id,
    agreed_price, cancel_reason, created_at, updated_at
`

type CancelServiceRequestParams struct {
	CancelReason pgtype.Text `json:"cancel_reason"`
	ID           int64       `json:"id"`
}

func (q *Queries) CancelServiceRequest(ctx context.Context, arg CancelServiceRequestParams) (ServiceRequest, error) {
	row := q.db.QueryRow(ctx, cancelServiceRequest, arg.CancelReason, arg.ID)
	var i ServiceRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ServiceID,
		&i.Description,
		&i.AddressText,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.MasterID,
		&i.AgreedPrice,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeServiceRequest = `-- name: CompleteServiceRequest :one
UPDATE service_requests
SET status = 'COMPLETED', updated_at = NOW()
WHERE id = $1 AND status = 'ASSIGNED'
RETURNING id, client_id, service_id, description, address_text, latitude, longitude, status, master_id,
    agreed_price, cancel_reason, created_at, updated_at
`

func (q *Queries) CompleteServiceRequest(ctx context.Context, id int64) (ServiceRequest, error) {
	row := q.db.QueryRow(ctx, completeServiceRequest, id)
	var i ServiceRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ServiceID,
		&i.Description,
		&i.AddressText,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.MasterID,
		&i.AgreedPrice,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOpenRequestsForMaster = `-- name: CountOpenRequestsForMaster :one
SELECT COUNT(*)::bigint AS count
FROM service_requests sr
JOIN master_specializations ms
    ON ms.service_id = sr.service_id AND ms.master_user_id = $1
WHERE sr.status = 'OPEN'
`

func (q *Queries) CountOpenRequestsForMaster(ctx context.Context, masterUserID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenRequestsForMaster, masterUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsAdmin = `-- name: CountRequestsAdmin :one
SELECT COUNT(*)::bigint AS count
FROM service_requests
WHERE ($1::text = '' OR status = $1::text)
`

func (q *Queries) CountRequestsAdmin(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsAdmin, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsByClient = `-- name: CountRequestsByClient :one
SELECT COUNT(*)::bigint AS count
FROM service_requests
WHERE client_id = $1
`

func (q *Queries) CountRequestsByClient(ctx context.Context, clientID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsByClient, clientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsByMaster = `-- name: CountRequestsByMaster :one
SELECT COUNT(*)::bigint AS count
FROM service_requests
WHERE master_id = $1
`

func (q *Queries) CountRequestsByMaster(ctx context.Context, masterID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsByMaster, masterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createServiceRequest = `-- name: CreateServiceRequest :one
INSERT INTO service_requests (client_id, service_id, description, address_text, latitude, longitude, status)
VALUES ($1, $2, $3, $4, $5, $6, 'OPEN')
RETURNING id, client_id, service_id, description, address_text, latitude, longitude, status, master_id,
    agreed_price, cancel_reason, created_at, updated_at
`

type CreateServiceRequestParams struct {
	ClientID    int64         `json:"client_id"`
	ServiceID   int64         `json:"service_id"`
	Description string        `json:"description"`
	AddressText string        `json:"address_text"`
	Latitude    pgtype.Float8 `json:"latitude"`
	Longitude   pgtype.Float8 `json:"longitude"`
}

func (q *Queries) CreateServiceRequest(ctx context.Context, arg CreateServiceRequestParams) (ServiceRequest, error) {
	row := q.db.QueryRow(ctx, createServiceRequest,
		arg.ClientID,
		arg.ServiceID,
		arg.Description,
		arg.AddressText,
		arg.Latitude,
		arg.Longitude,
	)
	var i ServiceRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ServiceID,
		&i.Description,
		&i.AddressText,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.MasterID,
		&i.AgreedPrice,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceRequestByID = `-- name: GetServiceRequestByID :one
SELECT id, client_id, service_id, description, address_text, latitude, longitude, status, master_id,
    agreed_price, cancel_reason, created_at, updated_at
FROM service_requests
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetServiceRequestByID(ctx context.Context, id int64) (ServiceRequest, error) {
	row := q.db.QueryRow(ctx, getServiceRequestByID, id)
	var i ServiceRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ServiceID,
		&i.Description,
		&i.AddressText,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.MasterID,
		&i.AgreedPrice,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOpenRequestsForMaster = `-- name: ListOpenRequestsForMaster :many
SELECT sr.id, sr.client_id, sr.service_id, sr.description, sr.address_text, sr.latitude, sr.longitude,
    sr.status, sr.master_id, sr.agreed_price, sr.cancel_reason, sr.created_at, sr.updated_at
FROM service_requests sr
JOIN master_specializations ms
    ON ms.service_id = sr.service_id AND ms.master_user_id = $1
WHERE sr.status = 'OPEN'
ORDER BY sr.created_at
LIMIT $3 OFFSET $2
`

type ListOpenRequestsForMasterParams struct {
	MasterUserID int64 `json:"master_user_id"`
	PageOffset   int32 `json:"page_offset"`
	PageLimit    int32 `json:"page_limit"`
}

// Pool of unclaimed requests, restricted to services the master is
// specialized in -- the hard server-side filter, not just a UI convenience.
func (q *Queries) ListOpenRequestsForMaster(ctx context.Context, arg ListOpenRequestsForMasterParams) ([]ServiceRequest, error) {
	rows, err := q.db.Query(ctx, listOpenRequestsForMaster, arg.MasterUserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceRequest{}
	for rows.Next() {
		var i ServiceRequest
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ServiceID,
			&i.Description,
			&i.AddressText,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.MasterID,
			&i.AgreedPrice,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsAdmin = `-- name: ListRequestsAdmin :many
SELECT id, client_id, service_id, description, address_text, latitude, longitude, status, master_id,
    agreed_price, cancel_reason, created_at, updated_at
FROM service_requests
WHERE ($1::text = '' OR status = $1::text)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListRequestsAdminParams struct {
	Status     string `json:"status"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

// status = ” means "no filter".
func (q *Queries) ListRequestsAdmin(ctx context.Context, arg ListRequestsAdminParams) ([]ServiceRequest, error) {
	rows, err := q.db.Query(ctx, listRequestsAdmin, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceRequest{}
	for rows.Next() {
		var i ServiceRequest
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ServiceID,
			&i.Description,
			&i.AddressText,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.MasterID,
			&i.AgreedPrice,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByClient = `-- name: ListRequestsByClient :many
SELECT id, client_id, service_id, description, address_text, latitude, longitude, status, master_id,
    agreed_price, cancel_reason, created_at, updated_at
FROM service_requests
WHERE client_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListRequestsByClientParams struct {
	ClientID   int64 `json:"client_id"`
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

func (q *Queries) ListRequestsByClient(ctx context.Context, arg ListRequestsByClientParams) ([]ServiceRequest, error) {
	rows, err := q.db.Query(ctx, listRequestsByClient, arg.ClientID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceRequest{}
	for rows.Next() {
		var i ServiceRequest
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ServiceID,
			&i.Description,
			&i.AddressText,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.MasterID,
			&i.AgreedPrice,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByMaster = `-- name: ListRequestsByMaster :many
SELECT id, client_id, service_id, description, address_text, latitude, longitude, status, master_id,
    agreed_price, cancel_reason, created_at, updated_at
FROM service_requests
WHERE master_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListRequestsByMasterParams struct {
	MasterID   pgtype.Int8 `json:"master_id"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) ListRequestsByMaster(ctx context.Context, arg ListRequestsByMasterParams) ([]ServiceRequest, error) {
	rows, err := q.db.Query(ctx, listRequestsByMaster, arg.MasterID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceRequest{}
	for rows.Next() {
		var i ServiceRequest
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ServiceID,
			&i.Description,
			&i.AddressText,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.MasterID,
			&i.AgreedPrice,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
