// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package notificationdb

import (
	"context"
)

const countNotificationsByUser = `-- name: CountNotificationsByUser :one
SELECT COUNT(*)::bigint AS count
FROM notifications
WHERE tenant_id = $1 AND user_id = $2
  AND ($3::bool = FALSE OR read_at IS NULL)
`

type CountNotificationsByUserParams struct {
	TenantID   int64 `json:"tenant_id"`
	UserID     int64 `json:"user_id"`
	UnreadOnly bool  `json:"unread_only"`
}

func (q *Queries) CountNotificationsByUser(ctx context.Context, arg CountNotificationsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByUser, arg.TenantID, arg.UserID, arg.UnreadOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadByUser = `-- name: CountUnreadByUser :one
SELECT COUNT(*)::bigint AS count
FROM notifications
WHERE tenant_id = $1 AND user_id = $2 AND read_at IS NULL
`

type CountUnreadByUserParams struct {
	TenantID int64 `json:"tenant_id"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) CountUnreadByUser(ctx context.Context, arg CountUnreadByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadByUser, arg.TenantID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (tenant_id, user_id, type, title, message, payload)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, user_id, type, title, message, payload, read_at, created_at
`

type CreateNotificationParams struct {
	TenantID int64  `json:"tenant_id"`
	UserID   int64  `json:"user_id"`
	Type     string `json:"type"`
	Title    string `json:"title"`
	Message  string `json:"message"`
	Payload  []byte `json:"payload"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.TenantID,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.Payload,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, tenant_id, user_id, type, title, message, payload, read_at, created_at
FROM notifications
WHERE tenant_id = $1 AND user_id = $2
  AND ($3::bool = FALSE OR read_at IS NULL)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListNotificationsByUserParams struct {
	TenantID   int64 `json:"tenant_id"`
	UserID     int64 `json:"user_id"`
	UnreadOnly bool  `json:"unread_only"`
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser,
		arg.TenantID,
		arg.UserID,
		arg.UnreadOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = NOW()
WHERE tenant_id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkAllNotificationsReadParams struct {
	TenantID int64 `json:"tenant_id"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, arg.TenantID, arg.UserID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND user_id = $3 AND read_at IS NULL
RETURNING id, tenant_id, user_id, type, title, message, payload, read_at, created_at
`

type MarkNotificationReadParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.TenantID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}
