// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package paymentdb

import (
	"context"
)

const countPaymentsAdmin = `-- name: CountPaymentsAdmin :one
SELECT COUNT(*)::bigint AS count
FROM payments
`

func (q *Queries) CountPaymentsAdmin(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (request_id, amount, platform_fee, status)
VALUES ($1, $2, $3, 'HELD')
RETURNING id, request_id, amount, platform_fee, status, created_at, updated_at
`

type CreatePaymentParams struct {
	RequestID   int64   `json:"request_id"`
	Amount      float64 `json:"amount"`
	PlatformFee float64 `json:"platform_fee"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment, arg.RequestID, arg.Amount, arg.PlatformFee)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Amount,
		&i.PlatformFee,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByRequestID = `-- name: GetPaymentByRequestID :one
SELECT id, request_id, amount, platform_fee, status, created_at, updated_at
FROM payments
WHERE request_id = $1
LIMIT 1
`

func (q *Queries) GetPaymentByRequestID(ctx context.Context, requestID int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByRequestID, requestID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Amount,
		&i.PlatformFee,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsAdmin = `-- name: ListPaymentsAdmin :many
SELECT id, request_id, amount, platform_fee, status, created_at, updated_at
FROM payments
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListPaymentsAdminParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

func (q *Queries) ListPaymentsAdmin(ctx context.Context, arg ListPaymentsAdminParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsAdmin, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Amount,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refundPayment = `-- name: RefundPayment :one
UPDATE payments
SET status = 'REFUNDED', updated_at = NOW()
WHERE request_id = $1 AND status = 'HELD'
RETURNING id, request_id, amount, platform_fee, status, created_at, updated_at
`

func (q *Queries) RefundPayment(ctx context.Context, requestID int64) (Payment, error) {
	row := q.db.QueryRow(ctx, refundPayment, requestID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Amount,
		&i.PlatformFee,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releasePayment = `-- name: ReleasePayment :one
UPDATE payments
SET status = 'RELEASED', updated_at = NOW()
WHERE request_id = $1 AND status = 'HELD'
RETURNING id, request_id, amount, platform_fee, status, created_at, updated_at
`

func (q *Queries) ReleasePayment(ctx context.Context, requestID int64) (Payment, error) {
	row := q.db.QueryRow(ctx, releasePayment, requestID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Amount,
		&i.PlatformFee,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
