// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package reviewdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVisibleReviewsByMaster = `-- name: CountVisibleReviewsByMaster :one
SELECT COUNT(*)::bigint AS count
FROM reviews
WHERE master_id = $1 AND hidden = false
`

func (q *Queries) CountVisibleReviewsByMaster(ctx context.Context, masterID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countVisibleReviewsByMaster, masterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (request_id, client_id, master_id, rating, comment, hidden)
VALUES ($1, $2, $3, $4, $5, false)
RETURNING id, request_id, client_id, master_id, rating, comment, hidden, created_at
`

type CreateReviewParams struct {
	RequestID int64       `json:"request_id"`
	ClientID  int64       `json:"client_id"`
	MasterID  int64       `json:"master_id"`
	Rating    int16       `json:"rating"`
	Comment   pgtype.Text `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.RequestID,
		arg.ClientID,
		arg.MasterID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ClientID,
		&i.MasterID,
		&i.Rating,
		&i.Comment,
		&i.Hidden,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, request_id, client_id, master_id, rating, comment, hidden, created_at
FROM reviews
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetReviewByID(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ClientID,
		&i.MasterID,
		&i.Rating,
		&i.Comment,
		&i.Hidden,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewByRequestID = `-- name: GetReviewByRequestID :one
SELECT id, request_id, client_id, master_id, rating, comment, hidden, created_at
FROM reviews
WHERE request_id = $1
LIMIT 1
`

func (q *Queries) GetReviewByRequestID(ctx context.Context, requestID int64) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByRequestID, requestID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ClientID,
		&i.MasterID,
		&i.Rating,
		&i.Comment,
		&i.Hidden,
		&i.CreatedAt,
	)
	return i, err
}

const hideReview = `-- name: HideReview :one
UPDATE reviews
SET hidden = true
WHERE id = $1
RETURNING id, request_id, client_id, master_id, rating, comment, hidden, created_at
`

func (q *Queries) HideReview(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRow(ctx, hideReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ClientID,
		&i.MasterID,
		&i.Rating,
		&i.Comment,
		&i.Hidden,
		&i.CreatedAt,
	)
	return i, err
}

const listVisibleReviewsByMaster = `-- name: ListVisibleReviewsByMaster :many
SELECT id, request_id, client_id, master_id, rating, comment, hidden, created_at
FROM reviews
WHERE master_id = $1 AND hidden = false
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListVisibleReviewsByMasterParams struct {
	MasterID   int64 `json:"master_id"`
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

func (q *Queries) ListVisibleReviewsByMaster(ctx context.Context, arg ListVisibleReviewsByMasterParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listVisibleReviewsByMaster, arg.MasterID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ClientID,
			&i.MasterID,
			&i.Rating,
			&i.Comment,
			&i.Hidden,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
