spring.application.name=curs3ProjectBack

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/curs3}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.sql.init.mode=never

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true

jwt.secret=5enjbH5/KpbWF7r4fZ6/ChiRbEjXfnOBr85Xxq9mBRo=
jwt.expiration=3600000

file.upload-dir=${FILE_UPLOAD_DIR:uploads}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
