// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package catalogdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO service_categories (parent_category_id, name)
VALUES ($1, $2)
RETURNING id, parent_category_id, name, active, created_at, updated_at
`

type CreateCategoryParams struct {
	ParentCategoryID pgtype.Int8 `json:"parent_category_id"`
	Name             string      `json:"name"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (ServiceCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.ParentCategoryID, arg.Name)
	var i ServiceCategory
	err := row.Scan(
		&i.ID,
		&i.ParentCategoryID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, parent_category_id, name, active, created_at, updated_at
FROM service_categories
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (ServiceCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i ServiceCategory
	err := row.Scan(
		&i.ID,
		&i.ParentCategoryID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, parent_category_id, name, active, created_at, updated_at
FROM service_categories
WHERE active = true
ORDER BY parent_category_id NULLS FIRST, name
`

// Every active category, top-level and subcategories alike -- the service
// layer groups children under their parent to build the nested tree.
func (q *Queries) ListActiveCategories(ctx context.Context) ([]ServiceCategory, error) {
	rows, err := q.db.Query(ctx, listActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceCategory{}
	for rows.Next() {
		var i ServiceCategory
		if err := rows.Scan(
			&i.ID,
			&i.ParentCategoryID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE service_categories
SET name = $1, active = $2, updated_at = NOW()
WHERE id = $3
RETURNING id, parent_category_id, name, active, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name   string `json:"name"`
	Active bool   `json:"active"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (ServiceCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.Name, arg.Active, arg.ID)
	var i ServiceCategory
	err := row.Scan(
		&i.ID,
		&i.ParentCategoryID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
