// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package catalogdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (category_id, name, description, price_from, price_to, unit, image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, category_id, name, description, price_from, price_to, unit, active, created_at, updated_at, image_url
`

type CreateServiceParams struct {
	CategoryID  int64       `json:"category_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	PriceFrom   *float64    `json:"price_from"`
	PriceTo     *float64    `json:"price_to"`
	Unit        pgtype.Text `json:"unit"`
	ImageUrl    pgtype.Text `json:"image_url"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.PriceFrom,
		arg.PriceTo,
		arg.Unit,
		arg.ImageUrl,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.PriceFrom,
		&i.PriceTo,
		&i.Unit,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, category_id, name, description, price_from, price_to, unit, active, created_at, updated_at, image_url
FROM services
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetServiceByID(ctx context.Context, id int64) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.PriceFrom,
		&i.PriceTo,
		&i.Unit,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const listActiveServices = `-- name: ListActiveServices :many
SELECT id, category_id, name, description, price_from, price_to, unit, active, created_at, updated_at, image_url
FROM services
WHERE active = true
  AND ($1::bigint = 0 OR category_id = $1::bigint)
ORDER BY name
`

// category_id = 0 means "no filter": every active service across the catalog.
func (q *Queries) ListActiveServices(ctx context.Context, categoryID int64) ([]Service, error) {
	rows, err := q.db.Query(ctx, listActiveServices, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.PriceFrom,
			&i.PriceTo,
			&i.Unit,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = $1, description = $2, price_from = $3,
    price_to = $4, unit = $5, active = $6, image_url = $7, updated_at = NOW()
WHERE id = $8
RETURNING id, category_id, name, description, price_from, price_to, unit, active, created_at, updated_at, image_url
`

type UpdateServiceParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	PriceFrom   *float64    `json:"price_from"`
	PriceTo     *float64    `json:"price_to"`
	Unit        pgtype.Text `json:"unit"`
	Active      bool        `json:"active"`
	ImageUrl    pgtype.Text `json:"image_url"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.Name,
		arg.Description,
		arg.PriceFrom,
		arg.PriceTo,
		arg.Unit,
		arg.Active,
		arg.ImageUrl,
		arg.ID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.PriceFrom,
		&i.PriceTo,
		&i.Unit,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}
