// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package chatdb

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (request_id, sender_id, text)
VALUES ($1, $2, $3)
RETURNING id, request_id, sender_id, text, created_at, read_at
`

type CreateMessageParams struct {
	RequestID int64  `json:"request_id"`
	SenderID  int64  `json:"sender_id"`
	Text      string `json:"text"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.RequestID, arg.SenderID, arg.Text)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.SenderID,
		&i.Text,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const listMessagesByRequestSince = `-- name: ListMessagesByRequestSince :many
SELECT id, request_id, sender_id, text, created_at, read_at
FROM messages
WHERE request_id = $1 AND id > $2::bigint
ORDER BY id
LIMIT $3
`

type ListMessagesByRequestSinceParams struct {
	RequestID int64 `json:"request_id"`
	SinceID   int64 `json:"since_id"`
	PageLimit int32 `json:"page_limit"`
}

// Cursor pagination: since_id = 0 returns from the beginning of the thread.
func (q *Queries) ListMessagesByRequestSince(ctx context.Context, arg ListMessagesByRequestSinceParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByRequestSince, arg.RequestID, arg.SinceID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.SenderID,
			&i.Text,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
