// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meters.sql

package meterdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMeter = `-- name: CreateMeter :one
INSERT INTO meters (type, serial_number, manufacture_year, verification_date, seal_state, transformation_ratio, inspection_act_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, type, serial_number, manufacture_year, verification_date, seal_state, transformation_ratio, inspection_act_id, created_at
`

type CreateMeterParams struct {
	Type                string      `json:"type"`
	SerialNumber        string      `json:"serial_number"`
	ManufactureYear     pgtype.Int4 `json:"manufacture_year"`
	VerificationDate    pgtype.Date `json:"verification_date"`
	SealState           pgtype.Text `json:"seal_state"`
	TransformationRatio pgtype.Int4 `json:"transformation_ratio"`
	InspectionActID     pgtype.Int8 `json:"inspection_act_id"`
}

func (q *Queries) CreateMeter(ctx context.Context, arg CreateMeterParams) (Meter, error) {
	row := q.db.QueryRow(ctx, createMeter,
		arg.Type,
		arg.SerialNumber,
		arg.ManufactureYear,
		arg.VerificationDate,
		arg.SealState,
		arg.TransformationRatio,
		arg.InspectionActID,
	)
	var i Meter
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.SerialNumber,
		&i.ManufactureYear,
		&i.VerificationDate,
		&i.SealState,
		&i.TransformationRatio,
		&i.InspectionActID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMeter = `-- name: DeleteMeter :exec
DELETE FROM meters
WHERE id = $1 AND inspection_act_id = $2
`

type DeleteMeterParams struct {
	ID              int64       `json:"id"`
	InspectionActID pgtype.Int8 `json:"inspection_act_id"`
}

func (q *Queries) DeleteMeter(ctx context.Context, arg DeleteMeterParams) error {
	_, err := q.db.Exec(ctx, deleteMeter, arg.ID, arg.InspectionActID)
	return err
}

const getMeterByID = `-- name: GetMeterByID :one
SELECT id, type, serial_number, manufacture_year, verification_date, seal_state, transformation_ratio, inspection_act_id, created_at
FROM meters
WHERE id = $1 AND inspection_act_id = $2
LIMIT 1
`

type GetMeterByIDParams struct {
	ID              int64       `json:"id"`
	InspectionActID pgtype.Int8 `json:"inspection_act_id"`
}

func (q *Queries) GetMeterByID(ctx context.Context, arg GetMeterByIDParams) (Meter, error) {
	row := q.db.QueryRow(ctx, getMeterByID, arg.ID, arg.InspectionActID)
	var i Meter
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.SerialNumber,
		&i.ManufactureYear,
		&i.VerificationDate,
		&i.SealState,
		&i.TransformationRatio,
		&i.InspectionActID,
		&i.CreatedAt,
	)
	return i, err
}

const listMetersByAct = `-- name: ListMetersByAct :many
SELECT id, type, serial_number, manufacture_year, verification_date, seal_state, transformation_ratio, inspection_act_id, created_at
FROM meters
WHERE inspection_act_id = $1
ORDER BY created_at
`

func (q *Queries) ListMetersByAct(ctx context.Context, inspectionActID pgtype.Int8) ([]Meter, error) {
	rows, err := q.db.Query(ctx, listMetersByAct, inspectionActID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meter{}
	for rows.Next() {
		var i Meter
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.SerialNumber,
			&i.ManufactureYear,
			&i.VerificationDate,
			&i.SealState,
			&i.TransformationRatio,
			&i.InspectionActID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeter = `-- name: UpdateMeter :one
UPDATE meters
SET type = $1,
    serial_number = $2,
    manufacture_year = $3,
    verification_date = $4,
    seal_state = $5,
    transformation_ratio = $6
WHERE id = $7 AND inspection_act_id = $8
RETURNING id, type, serial_number, manufacture_year, verification_date, seal_state, transformation_ratio, inspection_act_id, created_at
`

type UpdateMeterParams struct {
	Type                string      `json:"type"`
	SerialNumber        string      `json:"serial_number"`
	ManufactureYear     pgtype.Int4 `json:"manufacture_year"`
	VerificationDate    pgtype.Date `json:"verification_date"`
	SealState           pgtype.Text `json:"seal_state"`
	TransformationRatio pgtype.Int4 `json:"transformation_ratio"`
	ID                  int64       `json:"id"`
	InspectionActID     pgtype.Int8 `json:"inspection_act_id"`
}

func (q *Queries) UpdateMeter(ctx context.Context, arg UpdateMeterParams) (Meter, error) {
	row := q.db.QueryRow(ctx, updateMeter,
		arg.Type,
		arg.SerialNumber,
		arg.ManufactureYear,
		arg.VerificationDate,
		arg.SealState,
		arg.TransformationRatio,
		arg.ID,
		arg.InspectionActID,
	)
	var i Meter
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.SerialNumber,
		&i.ManufactureYear,
		&i.VerificationDate,
		&i.SealState,
		&i.TransformationRatio,
		&i.InspectionActID,
		&i.CreatedAt,
	)
	return i, err
}
