// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package consumerdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConsumers = `-- name: CountConsumers :one
SELECT COUNT(*)::bigint AS count
FROM organizations
WHERE tenant_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%')
`

type CountConsumersParams struct {
	TenantID int64  `json:"tenant_id"`
	Search   string `json:"search"`
}

func (q *Queries) CountConsumers(ctx context.Context, arg CountConsumersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConsumers, arg.TenantID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConsumer = `-- name: CreateConsumer :one
INSERT INTO organizations (name, type, description, tenant_id, active)
VALUES ($1, $2, $3, $4, TRUE)
RETURNING id, name, type, description, tenant_id, active, created_at, updated_at
`

type CreateConsumerParams struct {
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Description pgtype.Text `json:"description"`
	TenantID    int64       `json:"tenant_id"`
}

func (q *Queries) CreateConsumer(ctx context.Context, arg CreateConsumerParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createConsumer,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.TenantID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.TenantID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateConsumer = `-- name: DeactivateConsumer :one
UPDATE organizations
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, name, type, description, tenant_id, active, created_at, updated_at
`

type DeactivateConsumerParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) DeactivateConsumer(ctx context.Context, arg DeactivateConsumerParams) (Organization, error) {
	row := q.db.QueryRow(ctx, deactivateConsumer, arg.ID, arg.TenantID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.TenantID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsConsumerByID = `-- name: ExistsConsumerByID :one
SELECT EXISTS(
    SELECT 1 FROM organizations WHERE id = $1 AND tenant_id = $2 AND active = TRUE
) AS exists
`

type ExistsConsumerByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) ExistsConsumerByID(ctx context.Context, arg ExistsConsumerByIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsConsumerByID, arg.ID, arg.TenantID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getConsumerByID = `-- name: GetConsumerByID :one
SELECT id, name, type, description, tenant_id, active, created_at, updated_at
FROM organizations
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetConsumerByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetConsumerByID(ctx context.Context, arg GetConsumerByIDParams) (Organization, error) {
	row := q.db.QueryRow(ctx, getConsumerByID, arg.ID, arg.TenantID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.TenantID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConsumers = `-- name: ListConsumers :many
SELECT id, name, type, description, tenant_id, active, created_at, updated_at
FROM organizations
WHERE tenant_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%')
ORDER BY name
LIMIT $4 OFFSET $3
`

type ListConsumersParams struct {
	TenantID   int64  `json:"tenant_id"`
	Search     string `json:"search"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListConsumers(ctx context.Context, arg ListConsumersParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listConsumers,
		arg.TenantID,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.TenantID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConsumer = `-- name: UpdateConsumer :one
UPDATE organizations
SET name = $1,
    type = $2,
    description = $3,
    updated_at = NOW()
WHERE id = $4 AND tenant_id = $5
RETURNING id, name, type, description, tenant_id, active, created_at, updated_at
`

type UpdateConsumerParams struct {
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Description pgtype.Text `json:"description"`
	ID          int64       `json:"id"`
	TenantID    int64       `json:"tenant_id"`
}

func (q *Queries) UpdateConsumer(ctx context.Context, arg UpdateConsumerParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateConsumer,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.ID,
		arg.TenantID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.TenantID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
