// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package marketplacedb

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO service_categories (name)
VALUES ($1)
RETURNING id, name, active, created_at
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (ServiceCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, name)
	var i ServiceCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, active, created_at
FROM service_categories
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (ServiceCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i ServiceCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, name, active, created_at
FROM service_categories
WHERE active = TRUE
ORDER BY name
`

func (q *Queries) ListActiveCategories(ctx context.Context) ([]ServiceCategory, error) {
	rows, err := q.db.Query(ctx, listActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceCategory{}
	for rows.Next() {
		var i ServiceCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
