// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: masters.sql

package marketplacedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMasterSpecialization = `-- name: AddMasterSpecialization :exec
INSERT INTO master_specializations (master_user_id, service_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddMasterSpecializationParams struct {
	MasterUserID int64 `json:"master_user_id"`
	ServiceID    int64 `json:"service_id"`
}

func (q *Queries) AddMasterSpecialization(ctx context.Context, arg AddMasterSpecializationParams) error {
	_, err := q.db.Exec(ctx, addMasterSpecialization, arg.MasterUserID, arg.ServiceID)
	return err
}

const getMasterProfile = `-- name: GetMasterProfile :one
SELECT user_id, city, bio, created_at, updated_at
FROM master_profiles
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetMasterProfile(ctx context.Context, userID int64) (MasterProfile, error) {
	row := q.db.QueryRow(ctx, getMasterProfile, userID)
	var i MasterProfile
	err := row.Scan(
		&i.UserID,
		&i.City,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMasterSpecializationIDs = `-- name: ListMasterSpecializationIDs :many
SELECT service_id
FROM master_specializations
WHERE master_user_id = $1
`

func (q *Queries) ListMasterSpecializationIDs(ctx context.Context, masterUserID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listMasterSpecializationIDs, masterUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var service_id int64
		if err := rows.Scan(&service_id); err != nil {
			return nil, err
		}
		items = append(items, service_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const masterHasSpecialization = `-- name: MasterHasSpecialization :one
SELECT EXISTS (
    SELECT 1 FROM master_specializations
    WHERE master_user_id = $1 AND service_id = $2
) AS has_specialization
`

type MasterHasSpecializationParams struct {
	MasterUserID int64 `json:"master_user_id"`
	ServiceID    int64 `json:"service_id"`
}

func (q *Queries) MasterHasSpecialization(ctx context.Context, arg MasterHasSpecializationParams) (bool, error) {
	row := q.db.QueryRow(ctx, masterHasSpecialization, arg.MasterUserID, arg.ServiceID)
	var has_specialization bool
	err := row.Scan(&has_specialization)
	return has_specialization, err
}

const replaceMasterSpecializations = `-- name: ReplaceMasterSpecializations :exec
DELETE FROM master_specializations WHERE master_user_id = $1
`

func (q *Queries) ReplaceMasterSpecializations(ctx context.Context, masterUserID int64) error {
	_, err := q.db.Exec(ctx, replaceMasterSpecializations, masterUserID)
	return err
}

const upsertMasterProfile = `-- name: UpsertMasterProfile :one
INSERT INTO master_profiles (user_id, city, bio, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id) DO UPDATE
SET city = EXCLUDED.city, bio = EXCLUDED.bio, updated_at = NOW()
RETURNING user_id, city, bio, created_at, updated_at
`

type UpsertMasterProfileParams struct {
	UserID int64       `json:"user_id"`
	City   pgtype.Text `json:"city"`
	Bio    pgtype.Text `json:"bio"`
}

func (q *Queries) UpsertMasterProfile(ctx context.Context, arg UpsertMasterProfileParams) (MasterProfile, error) {
	row := q.db.QueryRow(ctx, upsertMasterProfile, arg.UserID, arg.City, arg.Bio)
	var i MasterProfile
	err := row.Scan(
		&i.UserID,
		&i.City,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
