// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offerings.sql

package marketplacedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (category_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, category_id, name, description, active, created_at
`

type CreateServiceParams struct {
	CategoryID  int64       `json:"category_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService, arg.CategoryID, arg.Name, arg.Description)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, category_id, name, description, active, created_at
FROM services
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetServiceByID(ctx context.Context, id int64) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveServices = `-- name: ListActiveServices :many
SELECT id, category_id, name, description, active, created_at
FROM services
WHERE active = TRUE
  AND ($1::bigint = 0 OR category_id = $1::bigint)
ORDER BY name
`

func (q *Queries) ListActiveServices(ctx context.Context, categoryID int64) ([]Service, error) {
	rows, err := q.db.Query(ctx, listActiveServices, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByIDs = `-- name: ListServicesByIDs :many
SELECT id, category_id, name, description, active, created_at
FROM services
WHERE id = ANY($1::bigint[])
`

func (q *Queries) ListServicesByIDs(ctx context.Context, ids []int64) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
