// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package orgdb

import (
	"context"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, code, plan, active)
VALUES ($1, $2, $3, $4)
RETURNING id, name, code, plan, active, created_at
`

type CreateTenantParams struct {
	Name   string `json:"name"`
	Code   string `json:"code"`
	Plan   string `json:"plan"`
	Active bool   `json:"active"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Code,
		arg.Plan,
		arg.Active,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Plan,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateTenant = `-- name: DeactivateTenant :one
UPDATE tenants
SET active = FALSE
WHERE id = $1
RETURNING id, name, code, plan, active, created_at
`

func (q *Queries) DeactivateTenant(ctx context.Context, id int64) (Tenant, error) {
	row := q.db.QueryRow(ctx, deactivateTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Plan,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const existsTenantByCode = `-- name: ExistsTenantByCode :one
SELECT EXISTS(
    SELECT 1 FROM tenants WHERE LOWER(code) = LOWER($1)
) AS exists
`

func (q *Queries) ExistsTenantByCode(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, existsTenantByCode, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsTenantByName = `-- name: ExistsTenantByName :one
SELECT EXISTS(
    SELECT 1 FROM tenants WHERE LOWER(name) = LOWER($1)
) AS exists
`

func (q *Queries) ExistsTenantByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, existsTenantByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getTenantByCode = `-- name: GetTenantByCode :one
SELECT id, name, code, plan, active, created_at
FROM tenants
WHERE LOWER(code) = LOWER($1)
LIMIT 1
`

func (q *Queries) GetTenantByCode(ctx context.Context, code string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByCode, code)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Plan,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, code, plan, active, created_at
FROM tenants
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id int64) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Plan,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, code, plan, active, created_at
FROM tenants
ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Plan,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantPlan = `-- name: UpdateTenantPlan :one
UPDATE tenants
SET plan = $1
WHERE id = $2
RETURNING id, name, code, plan, active, created_at
`

type UpdateTenantPlanParams struct {
	Plan string `json:"plan"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateTenantPlan(ctx context.Context, arg UpdateTenantPlanParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantPlan, arg.Plan, arg.ID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Plan,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
