// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package photodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (
    filename, note, tenant_id, inspection_act_id, replacement_act_id,
    original_filename, content_type, size_bytes, uploaded_by
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
RETURNING id, filename, note, tenant_id, inspection_act_id, replacement_act_id,
    original_filename, content_type, size_bytes, uploaded_by, created_at
`

type CreatePhotoParams struct {
	Filename         string      `json:"filename"`
	Note             pgtype.Text `json:"note"`
	TenantID         int64       `json:"tenant_id"`
	InspectionActID  pgtype.Int8 `json:"inspection_act_id"`
	ReplacementActID pgtype.Int8 `json:"replacement_act_id"`
	OriginalFilename string      `json:"original_filename"`
	ContentType      string      `json:"content_type"`
	SizeBytes        int64       `json:"size_bytes"`
	UploadedBy       pgtype.Int8 `json:"uploaded_by"`
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, createPhoto,
		arg.Filename,
		arg.Note,
		arg.TenantID,
		arg.InspectionActID,
		arg.ReplacementActID,
		arg.OriginalFilename,
		arg.ContentType,
		arg.SizeBytes,
		arg.UploadedBy,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Note,
		&i.TenantID,
		&i.InspectionActID,
		&i.ReplacementActID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deletePhoto = `-- name: DeletePhoto :one
DELETE FROM photos
WHERE id = $1 AND tenant_id = $2
RETURNING id, filename, note, tenant_id, inspection_act_id, replacement_act_id,
    original_filename, content_type, size_bytes, uploaded_by, created_at
`

type DeletePhotoParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) DeletePhoto(ctx context.Context, arg DeletePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, deletePhoto, arg.ID, arg.TenantID)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Note,
		&i.TenantID,
		&i.InspectionActID,
		&i.ReplacementActID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPhotoByID = `-- name: GetPhotoByID :one
SELECT id, filename, note, tenant_id, inspection_act_id, replacement_act_id,
    original_filename, content_type, size_bytes, uploaded_by, created_at
FROM photos
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetPhotoByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetPhotoByID(ctx context.Context, arg GetPhotoByIDParams) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhotoByID, arg.ID, arg.TenantID)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Note,
		&i.TenantID,
		&i.InspectionActID,
		&i.ReplacementActID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPhotosByInspectionAct = `-- name: ListPhotosByInspectionAct :many
SELECT id, filename, note, tenant_id, inspection_act_id, replacement_act_id,
    original_filename, content_type, size_bytes, uploaded_by, created_at
FROM photos
WHERE inspection_act_id = $1
ORDER BY created_at
`

func (q *Queries) ListPhotosByInspectionAct(ctx context.Context, inspectionActID pgtype.Int8) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listPhotosByInspectionAct, inspectionActID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Note,
			&i.TenantID,
			&i.InspectionActID,
			&i.ReplacementActID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosByReplacementAct = `-- name: ListPhotosByReplacementAct :many
SELECT id, filename, note, tenant_id, inspection_act_id, replacement_act_id,
    original_filename, content_type, size_bytes, uploaded_by, created_at
FROM photos
WHERE replacement_act_id = $1
ORDER BY created_at
`

func (q *Queries) ListPhotosByReplacementAct(ctx context.Context, replacementActID pgtype.Int8) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listPhotosByReplacementAct, replacementActID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Note,
			&i.TenantID,
			&i.InspectionActID,
			&i.ReplacementActID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
