// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addresses.sql

package addressdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAddresses = `-- name: CountAddresses :one
SELECT COUNT(*)::bigint AS count
FROM addresses
WHERE tenant_id = $1
  AND ($2::text = '' OR street ILIKE '%' || $2::text || '%' OR house ILIKE '%' || $2::text || '%')
  AND ($3::bigint = 0 OR consumer_id = $3::bigint)
`

type CountAddressesParams struct {
	TenantID   int64  `json:"tenant_id"`
	Search     string `json:"search"`
	ConsumerID int64  `json:"consumer_id"`
}

func (q *Queries) CountAddresses(ctx context.Context, arg CountAddressesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAddresses, arg.TenantID, arg.Search, arg.ConsumerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (street, house, building, apartment, tenant_id, consumer_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, street, house, building, apartment, tenant_id, consumer_id, created_at, updated_at
`

type CreateAddressParams struct {
	Street     string      `json:"street"`
	House      string      `json:"house"`
	Building   pgtype.Text `json:"building"`
	Apartment  pgtype.Text `json:"apartment"`
	TenantID   int64       `json:"tenant_id"`
	ConsumerID pgtype.Int8 `json:"consumer_id"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.Street,
		arg.House,
		arg.Building,
		arg.Apartment,
		arg.TenantID,
		arg.ConsumerID,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Street,
		&i.House,
		&i.Building,
		&i.Apartment,
		&i.TenantID,
		&i.ConsumerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsAddressByID = `-- name: ExistsAddressByID :one
SELECT EXISTS(
    SELECT 1 FROM addresses WHERE id = $1 AND tenant_id = $2
) AS exists
`

type ExistsAddressByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) ExistsAddressByID(ctx context.Context, arg ExistsAddressByIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsAddressByID, arg.ID, arg.TenantID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, street, house, building, apartment, tenant_id, consumer_id, created_at, updated_at
FROM addresses
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetAddressByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetAddressByID(ctx context.Context, arg GetAddressByIDParams) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressByID, arg.ID, arg.TenantID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Street,
		&i.House,
		&i.Building,
		&i.Apartment,
		&i.TenantID,
		&i.ConsumerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddresses = `-- name: ListAddresses :many
SELECT id, street, house, building, apartment, tenant_id, consumer_id, created_at, updated_at
FROM addresses
WHERE tenant_id = $1
  AND ($2::text = '' OR street ILIKE '%' || $2::text || '%' OR house ILIKE '%' || $2::text || '%')
  AND ($3::bigint = 0 OR consumer_id = $3::bigint)
ORDER BY street, house
LIMIT $5 OFFSET $4
`

type ListAddressesParams struct {
	TenantID   int64  `json:"tenant_id"`
	Search     string `json:"search"`
	ConsumerID int64  `json:"consumer_id"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListAddresses(ctx context.Context, arg ListAddressesParams) ([]Address, error) {
	rows, err := q.db.Query(ctx, listAddresses,
		arg.TenantID,
		arg.Search,
		arg.ConsumerID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.Street,
			&i.House,
			&i.Building,
			&i.Apartment,
			&i.TenantID,
			&i.ConsumerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE addresses
SET street = $1,
    house = $2,
    building = $3,
    apartment = $4,
    consumer_id = $5,
    updated_at = NOW()
WHERE id = $6 AND tenant_id = $7
RETURNING id, street, house, building, apartment, tenant_id, consumer_id, created_at, updated_at
`

type UpdateAddressParams struct {
	Street     string      `json:"street"`
	House      string      `json:"house"`
	Building   pgtype.Text `json:"building"`
	Apartment  pgtype.Text `json:"apartment"`
	ConsumerID pgtype.Int8 `json:"consumer_id"`
	ID         int64       `json:"id"`
	TenantID   int64       `json:"tenant_id"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.Street,
		arg.House,
		arg.Building,
		arg.Apartment,
		arg.ConsumerID,
		arg.ID,
		arg.TenantID,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Street,
		&i.House,
		&i.Building,
		&i.Apartment,
		&i.TenantID,
		&i.ConsumerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
