// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*)::bigint AS count
FROM users
WHERE role = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByTenantAndRole = `-- name: CountUsersByTenantAndRole :one
SELECT COUNT(*)::bigint AS count
FROM users
WHERE tenant_id = $1::bigint
  AND ($2::text = '' OR role = $2::text)
`

type CountUsersByTenantAndRoleParams struct {
	TenantID int64  `json:"tenant_id"`
	Role     string `json:"role"`
}

func (q *Queries) CountUsersByTenantAndRole(ctx context.Context, arg CountUsersByTenantAndRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByTenantAndRole, arg.TenantID, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByTenantID = `-- name: CountUsersByTenantID :one
SELECT COUNT(*)::bigint AS count
FROM users
WHERE tenant_id = $1::bigint
`

func (q *Queries) CountUsersByTenantID(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByTenantID, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at, revoked_at
`

type CreateRefreshTokenParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, full_name, role, tenant_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, password, full_name, role, tenant_id, created_at
`

type CreateUserParams struct {
	Username string      `json:"username"`
	Password string      `json:"password"`
	FullName pgtype.Text `json:"full_name"`
	Role     string      `json:"role"`
	TenantID pgtype.Int8 `json:"tenant_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.FullName,
		arg.Role,
		arg.TenantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Role,
		&i.TenantID,
		&i.CreatedAt,
	)
	return i, err
}

const existsPlatformUser = `-- name: ExistsPlatformUser :one
SELECT EXISTS(
    SELECT 1
    FROM users
    WHERE tenant_id IS NULL
      AND LOWER(username) = LOWER($1)
) AS exists
`

func (q *Queries) ExistsPlatformUser(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, existsPlatformUser, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUserInTenant = `-- name: ExistsUserInTenant :one
SELECT EXISTS(
    SELECT 1
    FROM users
    WHERE tenant_id = $1
      AND LOWER(username) = LOWER($2)
) AS exists
`

type ExistsUserInTenantParams struct {
	TenantID pgtype.Int8 `json:"tenant_id"`
	Username string      `json:"username"`
}

func (q *Queries) ExistsUserInTenant(ctx context.Context, arg ExistsUserInTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserInTenant, arg.TenantID, arg.Username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at
FROM refresh_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, full_name, role, tenant_id, created_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Role,
		&i.TenantID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPlatformUsername = `-- name: GetUserByPlatformUsername :one
SELECT id, username, password, full_name, role, tenant_id, created_at
FROM users
WHERE tenant_id IS NULL AND LOWER(username) = LOWER($1)
LIMIT 1
`

func (q *Queries) GetUserByPlatformUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPlatformUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Role,
		&i.TenantID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByTenantCodeAndUsername = `-- name: GetUserByTenantCodeAndUsername :one
SELECT u.id, u.username, u.password, u.full_name, u.role, u.tenant_id, u.created_at
FROM users u
JOIN tenants t ON t.id = u.tenant_id
WHERE LOWER(t.code) = LOWER($1)
  AND LOWER(u.username) = LOWER($2)
LIMIT 1
`

type GetUserByTenantCodeAndUsernameParams struct {
	TenantCode string `json:"tenant_code"`
	Username   string `json:"username"`
}

func (q *Queries) GetUserByTenantCodeAndUsername(ctx context.Context, arg GetUserByTenantCodeAndUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTenantCodeAndUsername, arg.TenantCode, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Role,
		&i.TenantID,
		&i.CreatedAt,
	)
	return i, err
}

const listUsersByTenant = `-- name: ListUsersByTenant :many
SELECT id, username, password, full_name, role, tenant_id, created_at
FROM users
WHERE tenant_id = $1::bigint
  AND ($2::text = '' OR role = $2::text)
ORDER BY full_name
LIMIT $4 OFFSET $3
`

type ListUsersByTenantParams struct {
	TenantID   int64  `json:"tenant_id"`
	Role       string `json:"role"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListUsersByTenant(ctx context.Context, arg ListUsersByTenantParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenant,
		arg.TenantID,
		arg.Role,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.FullName,
			&i.Role,
			&i.TenantID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeUserRefreshTokens, userID)
	return err
}
