// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inspection_acts.sql

package actdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInspectionAct = `-- name: CreateInspectionAct :one
INSERT INTO inspection_acts (task_id, tenant_id, address_id, inspection_date, consumer_id, inspection_type, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, task_id, tenant_id, address_id, inspection_date, consumer_id, inspection_type, notes, created_at, updated_at
`

type CreateInspectionActParams struct {
	TaskID         pgtype.Int8 `json:"task_id"`
	TenantID       int64       `json:"tenant_id"`
	AddressID      int64       `json:"address_id"`
	InspectionDate pgtype.Date `json:"inspection_date"`
	ConsumerID     pgtype.Int8 `json:"consumer_id"`
	InspectionType pgtype.Text `json:"inspection_type"`
	Notes          pgtype.Text `json:"notes"`
}

func (q *Queries) CreateInspectionAct(ctx context.Context, arg CreateInspectionActParams) (InspectionAct, error) {
	row := q.db.QueryRow(ctx, createInspectionAct,
		arg.TaskID,
		arg.TenantID,
		arg.AddressID,
		arg.InspectionDate,
		arg.ConsumerID,
		arg.InspectionType,
		arg.Notes,
	)
	var i InspectionAct
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TenantID,
		&i.AddressID,
		&i.InspectionDate,
		&i.ConsumerID,
		&i.InspectionType,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsInspectionActByTaskID = `-- name: ExistsInspectionActByTaskID :one
SELECT EXISTS(SELECT 1 FROM inspection_acts WHERE task_id = $1) AS exists
`

func (q *Queries) ExistsInspectionActByTaskID(ctx context.Context, taskID pgtype.Int8) (bool, error) {
	row := q.db.QueryRow(ctx, existsInspectionActByTaskID, taskID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getInspectionActByID = `-- name: GetInspectionActByID :one
SELECT id, task_id, tenant_id, address_id, inspection_date, consumer_id, inspection_type, notes, created_at, updated_at
FROM inspection_acts
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetInspectionActByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetInspectionActByID(ctx context.Context, arg GetInspectionActByIDParams) (InspectionAct, error) {
	row := q.db.QueryRow(ctx, getInspectionActByID, arg.ID, arg.TenantID)
	var i InspectionAct
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TenantID,
		&i.AddressID,
		&i.InspectionDate,
		&i.ConsumerID,
		&i.InspectionType,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInspectionActByTaskID = `-- name: GetInspectionActByTaskID :one
SELECT id, task_id, tenant_id, address_id, inspection_date, consumer_id, inspection_type, notes, created_at, updated_at
FROM inspection_acts
WHERE task_id = $1 AND tenant_id = $2
LIMIT 1
`

type GetInspectionActByTaskIDParams struct {
	TaskID   pgtype.Int8 `json:"task_id"`
	TenantID int64       `json:"tenant_id"`
}

func (q *Queries) GetInspectionActByTaskID(ctx context.Context, arg GetInspectionActByTaskIDParams) (InspectionAct, error) {
	row := q.db.QueryRow(ctx, getInspectionActByTaskID, arg.TaskID, arg.TenantID)
	var i InspectionAct
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TenantID,
		&i.AddressID,
		&i.InspectionDate,
		&i.ConsumerID,
		&i.InspectionType,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInspectionAct = `-- name: UpdateInspectionAct :one
UPDATE inspection_acts
SET inspection_date = $1,
    consumer_id = $2,
    inspection_type = $3,
    notes = $4,
    updated_at = NOW()
WHERE id = $5 AND tenant_id = $6
RETURNING id, task_id, tenant_id, address_id, inspection_date, consumer_id, inspection_type, notes, created_at, updated_at
`

type UpdateInspectionActParams struct {
	InspectionDate pgtype.Date `json:"inspection_date"`
	ConsumerID     pgtype.Int8 `json:"consumer_id"`
	InspectionType pgtype.Text `json:"inspection_type"`
	Notes          pgtype.Text `json:"notes"`
	ID             int64       `json:"id"`
	TenantID       int64       `json:"tenant_id"`
}

func (q *Queries) UpdateInspectionAct(ctx context.Context, arg UpdateInspectionActParams) (InspectionAct, error) {
	row := q.db.QueryRow(ctx, updateInspectionAct,
		arg.InspectionDate,
		arg.ConsumerID,
		arg.InspectionType,
		arg.Notes,
		arg.ID,
		arg.TenantID,
	)
	var i InspectionAct
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TenantID,
		&i.AddressID,
		&i.InspectionDate,
		&i.ConsumerID,
		&i.InspectionType,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
