// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replacement_acts.sql

package actdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReplacementAct = `-- name: CreateReplacementAct :one
INSERT INTO replacement_acts (
    task_id, tenant_id, address_id, account_number, installation_date,
    old_brand, old_serial_number, old_readings, new_brand, new_serial_number, new_readings
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
)
RETURNING id, task_id, tenant_id, address_id, account_number, installation_date,
    old_brand, old_serial_number, old_readings, new_brand, new_serial_number, new_readings,
    created_at, updated_at
`

type CreateReplacementActParams struct {
	TaskID           pgtype.Int8   `json:"task_id"`
	TenantID         int64         `json:"tenant_id"`
	AddressID        int64         `json:"address_id"`
	AccountNumber    string        `json:"account_number"`
	InstallationDate pgtype.Date   `json:"installation_date"`
	OldBrand         pgtype.Text   `json:"old_brand"`
	OldSerialNumber  pgtype.Text   `json:"old_serial_number"`
	OldReadings      pgtype.Float8 `json:"old_readings"`
	NewBrand         pgtype.Text   `json:"new_brand"`
	NewSerialNumber  pgtype.Text   `json:"new_serial_number"`
	NewReadings      pgtype.Float8 `json:"new_readings"`
}

func (q *Queries) CreateReplacementAct(ctx context.Context, arg CreateReplacementActParams) (ReplacementAct, error) {
	row := q.db.QueryRow(ctx, createReplacementAct,
		arg.TaskID,
		arg.TenantID,
		arg.AddressID,
		arg.AccountNumber,
		arg.InstallationDate,
		arg.OldBrand,
		arg.OldSerialNumber,
		arg.OldReadings,
		arg.NewBrand,
		arg.NewSerialNumber,
		arg.NewReadings,
	)
	var i ReplacementAct
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TenantID,
		&i.AddressID,
		&i.AccountNumber,
		&i.InstallationDate,
		&i.OldBrand,
		&i.OldSerialNumber,
		&i.OldReadings,
		&i.NewBrand,
		&i.NewSerialNumber,
		&i.NewReadings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsReplacementActByTaskID = `-- name: ExistsReplacementActByTaskID :one
SELECT EXISTS(SELECT 1 FROM replacement_acts WHERE task_id = $1) AS exists
`

func (q *Queries) ExistsReplacementActByTaskID(ctx context.Context, taskID pgtype.Int8) (bool, error) {
	row := q.db.QueryRow(ctx, existsReplacementActByTaskID, taskID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getReplacementActByID = `-- name: GetReplacementActByID :one
SELECT id, task_id, tenant_id, address_id, account_number, installation_date,
    old_brand, old_serial_number, old_readings, new_brand, new_serial_number, new_readings,
    created_at, updated_at
FROM replacement_acts
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetReplacementActByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetReplacementActByID(ctx context.Context, arg GetReplacementActByIDParams) (ReplacementAct, error) {
	row := q.db.QueryRow(ctx, getReplacementActByID, arg.ID, arg.TenantID)
	var i ReplacementAct
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TenantID,
		&i.AddressID,
		&i.AccountNumber,
		&i.InstallationDate,
		&i.OldBrand,
		&i.OldSerialNumber,
		&i.OldReadings,
		&i.NewBrand,
		&i.NewSerialNumber,
		&i.NewReadings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReplacementActByTaskID = `-- name: GetReplacementActByTaskID :one
SELECT id, task_id, tenant_id, address_id, account_number, installation_date,
    old_brand, old_serial_number, old_readings, new_brand, new_serial_number, new_readings,
    created_at, updated_at
FROM replacement_acts
WHERE task_id = $1 AND tenant_id = $2
LIMIT 1
`

type GetReplacementActByTaskIDParams struct {
	TaskID   pgtype.Int8 `json:"task_id"`
	TenantID int64       `json:"tenant_id"`
}

func (q *Queries) GetReplacementActByTaskID(ctx context.Context, arg GetReplacementActByTaskIDParams) (ReplacementAct, error) {
	row := q.db.QueryRow(ctx, getReplacementActByTaskID, arg.TaskID, arg.TenantID)
	var i ReplacementAct
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TenantID,
		&i.AddressID,
		&i.AccountNumber,
		&i.InstallationDate,
		&i.OldBrand,
		&i.OldSerialNumber,
		&i.OldReadings,
		&i.NewBrand,
		&i.NewSerialNumber,
		&i.NewReadings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReplacementAct = `-- name: UpdateReplacementAct :one
UPDATE replacement_acts
SET account_number = $1,
    installation_date = $2,
    old_brand = $3,
    old_serial_number = $4,
    old_readings = $5,
    new_brand = $6,
    new_serial_number = $7,
    new_readings = $8,
    updated_at = NOW()
WHERE id = $9 AND tenant_id = $10
RETURNING id, task_id, tenant_id, address_id, account_number, installation_date,
    old_brand, old_serial_number, old_readings, new_brand, new_serial_number, new_readings,
    created_at, updated_at
`

type UpdateReplacementActParams struct {
	AccountNumber    string        `json:"account_number"`
	InstallationDate pgtype.Date   `json:"installation_date"`
	OldBrand         pgtype.Text   `json:"old_brand"`
	OldSerialNumber  pgtype.Text   `json:"old_serial_number"`
	OldReadings      pgtype.Float8 `json:"old_readings"`
	NewBrand         pgtype.Text   `json:"new_brand"`
	NewSerialNumber  pgtype.Text   `json:"new_serial_number"`
	NewReadings      pgtype.Float8 `json:"new_readings"`
	ID               int64         `json:"id"`
	TenantID         int64         `json:"tenant_id"`
}

func (q *Queries) UpdateReplacementAct(ctx context.Context, arg UpdateReplacementActParams) (ReplacementAct, error) {
	row := q.db.QueryRow(ctx, updateReplacementAct,
		arg.AccountNumber,
		arg.InstallationDate,
		arg.OldBrand,
		arg.OldSerialNumber,
		arg.OldReadings,
		arg.NewBrand,
		arg.NewSerialNumber,
		arg.NewReadings,
		arg.ID,
		arg.TenantID,
	)
	var i ReplacementAct
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TenantID,
		&i.AddressID,
		&i.AccountNumber,
		&i.InstallationDate,
		&i.OldBrand,
		&i.OldSerialNumber,
		&i.OldReadings,
		&i.NewBrand,
		&i.NewSerialNumber,
		&i.NewReadings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
